services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: scoreboard
      POSTGRES_PASSWORD: scoreboard
      POSTGRES_DB: scoreboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=scoreboard
      - DB_USER=scoreboard
      - DB_PASSWORD=scoreboard

      
volumes:
  postgres_data:
