# Generated by Django 5.2 on 2025-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mechanic",
            name="name",
            field=models.CharField(
                choices=[
                    ("area_control", "Area Control"),
                    ("auction", "Auction"),
                    ("deck_building", "Deck Building"),
                    ("dice_rolling", "Dice Rolling"),
                    ("hand_management", "Hand Management"),
                    ("memory", "Memory"),
                    ("simulation", "Simulation"),
                    ("tile_laying", "Tile Laying"),
                    ("trick", "Trick Taking"),
                    ("worker_placement", "Worker Placement"),
                ],
                default="deck_building",
            ),
        ),
    ]
